# Generated by Django 4.2.4 on 2023-08-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
